### PR TITLE
Feature/harsh gurnani jenny mar/inputvalidation

### LINKED ISSUE #14: Add input validation to our input components
PR #11 creates an Input Text Component. When a user enters some text, we want to be able to validate it and render out relevant messages. 

Look at the image below - 
image
Note the different types of error messages (look at the colors green and red) and also how some have an icon at the beginning and some don't. 
## Example uses
image

- Note that the functionality you add to make this happen should be easily reusable at different location. You can come up with the best way to organize code. 
- I recommend looking at this term called [regular expressions](https://medium.com/factory-mind/regex-tutorial-a-simple-cheatsheet-by-examples-649dc1c3f285) for validation. 
- See if you can somehow have the parent component of the input field (one that uses it) define the entire error message and its styling (while building components always try to limit the work done by the component as much as possible)

## Resources
- In addition to google, ask ChatGPT - "swiftui how to add input validation" and see it do the magic! Best way to use ChatGPT is to always take its answers with a grain of salt so beware. But feel free to ask it any question you have and it has never disappointed me yet

### PR DESCRIPTION
**Pull request by HarshGurnani**
### Tracking Info

Resolves #14 

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

We added input validation functionality. The InputValidationText file is used to create a Text View that can display a message and a checkmark/exclamation mark that correlates to success or failure. In addition, we added a component called the InputValidationComponent, which takes in an array of functions and calls those functions with the text from the textbox. Those functions return a boolean value which determine if we display a success message or failure message.

- TODO

### Testing

We tested with test functions in the InputValidationComponent, as well as a Test View in the TextInputFieldComponent.

- TODO

### Confirmation of Change 

image (1)

image (2)

TODO...

### CODE REVIEW

**Comment by AmanKAggarwal** [comment]
can you rebase this branch off of main so that we will have the linting checks done here as well? Lmk if you don't understand rebase and I can discuss in the team meeting because it is very important and useful in git!

**Review by AmanKAggarwal — APPROVED** [review]
Awesome work!

**Comment by AmanKAggarwal** [comment]
Linked issue #14 to this PR

**Comment by AmanKAggarwal** [comment]
Leaving a comment here to make sure we don't forget
Change the spacing between the text box and the first error message (to match figma)
image

**Review by YashRavipati1 — APPROVED** [review]
Looks good!

**Pull request merged**
